# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - bastion

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: npm install, build, and test
        run: |
          cd bastion_csr
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: |
          cd bastion_csr
          zip -r release.zip . -x "node_modules/*" "test/*" "*.log" "*.git*"

      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls 
          echo "Contents of bastion_csr directory:"
          ls bastion_csr

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: bastion_csr/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_3C4CC0401FFA468B8F11A4FA4D7354E1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_0BF2664F269A4987BF7BA2416D2FE009 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E1874C2226B14A93AA16585C5BA15D1A }}

      - name: Debug - List files
        run: |
          echo "Current directory:"
          pwd
          echo "Contents of current directory:"
          ls 
          echo "Contents of bastion_csr directory:"
          ls bastion_csr

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bastion'
          package: release.zip

      - name: 'Post-deployment cleanup'
        run: rm bastion_csr/release.zip         

